INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('1', 'Seoul');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('2', 'Seoul');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('3', 'Busan');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('4', 'Daegu');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('5', 'Busan');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('6', 'Daegu');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('7', 'Gwangju');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('8', 'Gwangju');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('9', 'Gwangju');
INSERT INTO CITIES(PATIENT_ID, CITY_NAME)
VALUES ('10', 'Gwangju');

INSERT INTO STATES(COUNTRY_NAME)
VALUES ('Korea');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('Japan');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('China');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('Italy');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('Russia');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('England');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('USA');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('France');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('Spain');
INSERT INTO STATES(COUNTRY_NAME)
VALUES ('Belgium');

INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('1', 'Korea', '1992');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('2', 'Korea', '1993');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('3', 'Korea', '1994');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('4', 'Korea', '1995');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('5', 'Korea', '1996');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('6', 'Korea', '1997');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('7', 'Korea', '1998');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('8', 'Korea', '1999');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('9', 'Korea', '2000');
INSERT INTO PATIENT_POPULARITY(PATIENT_ID, COUNTRY_NAME, BD_YEAR)
VALUES ('10', 'Korea', '2001');
