select CITY_PAT, sum(PATIENT_COUNT)
from PATIENTS_POPULARITY
inner join CITIES1 using(patient_id) 
GROUP BY CITY_PAT;

select CITY_PAT,(SUM(PATIENT_COUNT)*100)/(select SUM(PATIENT_COUNT) from PATIENTS_POPULARITY)
from PATIENTS_POPULARITY
inner join CITIES1 using(patient_id) 
GROUP BY CITY_PAT;

select BD_YEAR, SUM(PATIENT_COUNT)
from PATIENTS_POPULARITY
GROUP BY BD_YEAR;
